sudo: required
services: docker
before_install:
   - docker-compose up --build -d
script:
  - docker-compose --env 'RAILS_ENV=test' web rails db:create
  - docker-compose --env 'RAILS_ENV=test' web rails db:migrate
  - docker-compose --env 'RAILS_ENV=test' web rails test

